apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{$.Values.spec.project}}-{{ .Values.spec.appName }}"
  name: "{{$.Values.spec.project}}-{{ .Values.spec.appName }}"
  namespace: "{{$.Values.spec.project}}-{{ .Values.spec.appName }}"
spec:
  type: NodePort
  ports:
  - port: {{ .Values.spec.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.spec.containerPort }}
  selector:
    app: "{{$.Values.spec.project}}-{{ .Values.spec.appName }}"